#!/system/bin/sh
# call a userinit.sh script if it's present on the sdcard
if [ -e /sd-ext/userinit.sh ];
then
   echo "--- Executing userinit.sh";
   busybox chmod +x /sd-ext/userinit.sh;
   /system/bin/sh /sd-ext/userinit.sh;
   setprop cm.userinit.active 1;
fi;

if [ -d /sd-ext/userinit.d ];
then
   busybox run-parts /sd-ext/userinit.d;
   setprop cm.userinit.active 1;
fi;
