#!/system/bin/sh
# call a userinit.sh script if it's present on the sdcard

if [ "$SD_EXT_DIRECTORY" == ""];
then
    SD_EXT_DIRECTORY = "/sd-ext";
fi;

if [ -e $SD_EXT_DIRECTORY/userinit.sh ];
then
   echo "--- Executing userinit.sh";
   busybox chmod +x $SD_EXT_DIRECTORY/userinit.sh;
   /system/bin/sh $SD_EXT_DIRECTORY/userinit.sh;
   setprop cm.userinit.active 1;
fi;

if [ -d $SD_EXT_DIRECTORY/userinit.d ];
then
   busybox run-parts $SD_EXT_DIRECTORY/userinit.d;
   setprop cm.userinit.active 1;
fi;
