mkdir -p proprietary

adb pull system/app/BugReport.apk proprietary
adb pull system/app/CarDock.apk proprietary
adb pull system/app/com.amazon.mp3.apk proprietary
adb pull system/app/EnhancedGoogleSearchProvider.apk proprietary
adb pull system/app/Facebook.apk proprietary
adb pull system/app/GenieWidget.apk proprietary
adb pull system/app/Gmail.apk proprietary
adb pull system/app/GmailProvider.apk proprietary
adb pull system/app/GoogleApps.apk proprietary
adb pull system/app/GoogleBackupTransport.apk proprietary
adb pull system/app/GoogleCheckin.apk proprietary
adb pull system/app/GoogleContactsSyncAdapter.apk proprietary
adb pull system/app/GoogleGoggles.apk proprietary
adb pull system/app/GooglePartnerSetup.apk proprietary
adb pull system/app/GoogleSettingsProvider.apk proprietary
adb pull system/app/GoogleSubscribedFeedsProvider.apk proprietary
adb pull system/app/googlevoice.apk proprietary
adb pull system/app/gtalkservice.apk proprietary
adb pull system/app/HtcCopyright.apk proprietary
adb pull system/app/LatinImeTutorial.apk proprietary
adb pull system/app/Maps.apk proprietary
adb pull system/app/MarketUpdater.apk proprietary
adb pull system/app/MediaUploader.apk proprietary
adb pull system/app/NetworkLocation.apk proprietary
adb pull system/app/PassionQuickOffice.apk proprietary
adb pull system/app/SetupWizard.apk proprietary
adb pull system/app/Street.apk proprietary
adb pull system/app/Talk.apk proprietary
adb pull system/app/TalkProvider.apk proprietary
adb pull system/app/Vending.apk proprietary
adb pull system/app/VoiceSearchWithKeyboard.apk proprietary
adb pull system/app/YouTube.apk proprietary
adb pull system/etc/permissions/com.google.android.datamessaging.xml proprietary
adb pull system/etc/permissions/com.google.android.gtalkservice.xml proprietary
adb pull system/etc/permissions/com.google.android.maps.xml proprietary
adb pull system/framework/com.google.android.gtalkservice.jar proprietary
adb pull system/framework/com.google.android.maps.jar proprietary
adb pull system/lib/libgtalk_jni.so proprietary
adb pull system/lib/libinterstitial.so proprietary
