#!/system/bin/sh
# call a userinit.sh script if it's present on the sdcard
if [ -e /system/sd/userinit.sh ];
then
    echo "--- Executing userinit.sh";
    busybox chmod +x /system/sd/userinit.sh;
    /system/bin/sh /system/sd/userinit.sh;
    setprop cm.userinit.active 1;
fi;

if [ -d /system/sd/userinit.d ];
then
    busybox run-parts /system/sd/userinit.d;
    setprop cm.userinit.active 1;
fi;
