#!/system/bin/sh
echo "+++ \"This is your world, these are your people. You can live for yourself today, or help build tomorrow for everyone.\""
echo "+++ Welcome to Android `getprop ro.build.version.release` / `getprop ro.modversion`";
