#!/system/bin/sh
echo "+++ \"In a world of deceit, open your eyes.  Don't be afraid and you realize......\""
echo "+++ Welcome to Android `getprop ro.build.version.release` / `getprop ro.modversion`";
